name: changeset

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies and build
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Create Release Pull Request
        uses: changesets/action@v1
        id: changeset/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESET}}